# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BUNGIE_NET_API_KEY: ${{ secrets.BUNGIE_NET_API_KEY }}

    strategy:
      matrix:
        node-version: [6.16, 7.10, 8.15, 9.11, 10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    #- run: npm ci
    - run: export BUNGIE_NET_API_KEY=$BUNGIE_NET_API_KEY
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
